<?php

return [

    /*
    |--------------------------------------------------------------------------
    | INVOICES
    |--------------------------------------------------------------------------
    */

    'title' => 'Invoicing',
    'subtitle' => 'Invoice and payment management',
    'new_invoice' => 'New invoice',

    /*
    |--------------------------------------------------------------------------
    | BUTTONS
    |--------------------------------------------------------------------------
    */

    'pdf_button' => 'PDF',

    /*
    |--------------------------------------------------------------------------
    | PAYMENT STATUS
    |--------------------------------------------------------------------------
    */

    'payment_status' => [

        'pending' => 'Pending payment',

        'in_process' => 'In process',

        'paid' => 'Paid',

        'cancelled' => 'Cancelled',

    ],

    /*
    |--------------------------------------------------------------------------
    | FINANCIAL SUMMARY
    |--------------------------------------------------------------------------
    */

    'financial' => [

        'pending_collection' => 'Pending collection',

        'total_collected' => 'Total collected',

        'total_invoiced' => 'Total invoiced',

    ],

    /*
    |--------------------------------------------------------------------------
    | FILTERS
    |--------------------------------------------------------------------------
    */

    'filters' => [

        'all' => 'All',

    ],

    /*
    |--------------------------------------------------------------------------
    | TABLE
    |--------------------------------------------------------------------------
    */

    'table' => [

        'title' => 'Invoices',

        'invoice' => 'Invoice',

        'company' => 'Company',

        'period' => 'Period',

        'subtotal' => 'Subtotal',

        'tax' => 'Tax',

        'total' => 'Total',

        'payment_status' => 'Payment status',

        'generated_by' => 'Generated by',

        'actions' => 'Actions',

    ],

    /*
    |--------------------------------------------------------------------------
    | ACTIONS
    |--------------------------------------------------------------------------
    */

    'actions' => [

        'view' => 'View',

    ],

    /*
    |--------------------------------------------------------------------------
    | MESSAGES
    |--------------------------------------------------------------------------
    */

    'no_invoices' => 'No invoices registered.',

    /*
    |--------------------------------------------------------------------------
    | INVOICE
    |--------------------------------------------------------------------------
    */

    'invoice' => 'Invoice',

    'invoices' => 'Invoices',

    'detail' => 'Invoice details',

    'invoice_information' => 'Invoice information',

    'invoice_number' => 'Invoice number',

    'company' => 'Company',

    'client' => 'Client',

    'period' => 'Period',

    'billing_period' => 'Billing period',

    'generated_by' => 'Generated by',

    'generated_at' => 'Generated on',

    'status' => 'Status',

    'current_status' => 'Current status',

    'payment_status_label' => 'Payment status',

    'generated' => 'Generated',

    /*
    |--------------------------------------------------------------------------
    | RECORDS
    |--------------------------------------------------------------------------
    */

    'included_records' => 'Included records',

    'records' => 'Records',

    'record' => 'Record',

    'date' => 'Date',

    'invoice_field' => 'Invoice',

    'paps' => 'PAPS',

    'services' => 'Services',

    'service' => 'Service',

    'amount' => 'Amount',

    'subtotal' => 'Subtotal',

    'no_records' => 'No records exist.',

    'no_services' => 'No services registered.',

    /*
    |--------------------------------------------------------------------------
    | CHARGES
    |--------------------------------------------------------------------------
    */

    'additional_charge' => 'Additional charge',

    'shipping' => 'Shipping',

    'handling' => 'Handling',

    'shipping_handling' => 'Shipping & Handling',

    /*
    |--------------------------------------------------------------------------
    | TOTALS
    |--------------------------------------------------------------------------
    */

    'records_subtotal' => 'Records subtotal',

    'tax_rate' => 'Tax rate',

    'tax' => 'Tax',

    'total' => 'Total',

    /*
    |--------------------------------------------------------------------------
    | GENERAL ACTIONS
    |--------------------------------------------------------------------------
    */

    'back' => '← Invoices',

    'save_status' => 'Save status',

    /*
    |--------------------------------------------------------------------------
    | GENERAL MESSAGES
    |--------------------------------------------------------------------------
    */

    'no_billing_company' => 'No billing company was specified.',

    'no_data' => '—',

    /*
    |--------------------------------------------------------------------------
    | CREATE INVOICE
    |--------------------------------------------------------------------------
    */

    'create' => [

        'title' => 'Generate invoice',

        'subtitle' => 'Select the records and configure the billing information.',

        'configuration' => 'Invoice configuration',

        'billing_company' => 'Billing company',

        'select_company' => 'Select company',

        'add_company' => 'Add company',

        'broker' => 'Broker',

        'without_broker' => 'Without broker',

        'add_broker' => 'Add broker',

        'consignee' => 'Consignee',

        'without_consignee' => 'Without consignee',

        'add_consignee' => 'Add consignee',

        'billing_type' => 'Billing type',

        'single_company' => 'Single company',

        'multiple_companies' => 'Multiple companies',

        'record_company' => 'Record company',

        'record_companies' => 'Record companies',

        'period_start' => 'Start period',

        'period_end' => 'End period',

        /*
        |--------------------------------------------------------------------------
        | OPTIONS
        |--------------------------------------------------------------------------
        */

        'invoice_options' => 'Invoice options',

        'apply_tax' => 'Apply tax',

        'shipping_handling' => 'Shipping / Handling',

        'percent' => '%',

        /*
        |--------------------------------------------------------------------------
        | RECORD SEARCH
        |--------------------------------------------------------------------------
        */

        'search_records' => 'Search records',

        'available_records' => 'Available records',

        'select_company_period' => 'Select a company and a period to search for records.',

        /*
        |--------------------------------------------------------------------------
        | RECORD TABLE
        |--------------------------------------------------------------------------
        */

        'table' => [

            'date' => 'Date',

            'company' => 'Company',

            'invoice_number' => 'Invoice number',

            'paps' => 'PAPS',

            'fact' => 'FACT',

            'origin' => 'Entry',

            'destination' => 'Exit',

            'services' => 'Services',

            'billing_invoice' => 'Billing invoice number',

            'billing_paps' => 'Billing PAPS',

            'pallets' => 'Pallets',

            'additional_charge' => 'Additional charge',

            'amount' => 'Amount',

        ],

        /*
        |--------------------------------------------------------------------------
        | SUMMARY
        |--------------------------------------------------------------------------
        */

        'summary' => 'Summary',

        'selected_records' => 'Selected records',

        'subtotal' => 'Subtotal',

        'tax' => 'Tax',

        'total' => 'Total',

        /*
        |--------------------------------------------------------------------------
        | COMMENTS
        |--------------------------------------------------------------------------
        */

        'comments' => 'Comments',

        'comments_placeholder' => 'Additional comments for the invoice...',

        /*
        |--------------------------------------------------------------------------
        | ACTIONS
        |--------------------------------------------------------------------------
        */

        'cancel' => 'Cancel',

        'generate_invoice' => 'Generate invoice',

        /*
        |--------------------------------------------------------------------------
        | NEW COMPANY MODAL
        |--------------------------------------------------------------------------
        */

        'company_modal' => [

            'title' => 'New company',

            'name' => 'Name',

            'code' => 'Code',

            'tax_id' => 'Tax ID',

            'save' => 'Save company',

        ],

        /*
        |--------------------------------------------------------------------------
        | NEW BROKER MODAL
        |--------------------------------------------------------------------------
        */

        'broker_modal' => [

            'title' => 'New broker',

            'name' => 'Name',

            'save' => 'Save broker',

        ],

        /*
        |--------------------------------------------------------------------------
        | NEW CONSIGNEE MODAL
        |--------------------------------------------------------------------------
        */

        'consignee_modal' => [

            'title' => 'New consignee',

            'name' => 'Name',

            'save' => 'Save consignee',

        ],

        /*
        |--------------------------------------------------------------------------
        | JAVASCRIPT
        |--------------------------------------------------------------------------
        */

        'js' => [

            'company_create_error' =>
                'Unable to create the company.',

            'company_create_exception' =>
                'An error occurred while creating the company.',

            'broker_create_error' =>
                'Unable to create the broker.',

            'broker_create_exception' =>
                'An error occurred while creating the broker.',

            'consignee_create_error' =>
                'Unable to create the consignee.',

            'consignee_create_exception' =>
                'An error occurred while creating the consignee.',

            'select_company' =>
                'Select at least one company to search for records.',

            'select_period' =>
                'Select the invoice period.',

            'searching_records' =>
                'Searching records...',

            'get_records_error' =>
                'Unable to retrieve the records.',

            'no_records_found' =>
                'No records were found for the selected period.',

            'service' =>
                'Service',

            'no_services' =>
                'No services',

            'services_label' =>
                'Services:',

            'additional_charge' =>
                'Additional charge',

            'select_record' =>
                'Select at least one record to generate the invoice.',

            'generating' =>
                'Generating...',

        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | PDF
    |--------------------------------------------------------------------------
    */

    'pdf' => [

        'invoice' => 'INVOICE',

        'invoice_date' => 'INVOICE DATE:',

        'receiving_date' => 'RECEIVING DATE:',

        'invoice_number' => 'INVOICE #',

        'bill_to' => 'Bill To',

        'invoice_information' => 'Invoice information',

        'period' => 'Period:',

        'generated_by' => 'Generated by:',

        'billing_period' => 'Billing period:',

        'date' => 'Date',

        'company' => 'Company',

        'invoice' => 'Invoice',

        'paps' => 'PAPS',

        'services' => 'Services',

        'comments' => 'Comments',

        'amount' => 'Amount',

        'service' => 'Service',

        'additional_charge' => 'Additional charge',

        'no_records' => 'No records available.',

        'no_service' => '—',

        'notes' => 'Notes',

        'records_subtotal' => 'Records subtotal',

        'shipping' => 'Shipping',

        'handling' => 'Handling',

        'tax_rate' => 'Tax rate',

        'total' => 'TOTAL',

        'phone' => 'Phone:',

        'tax_id' => 'Tax ID:',

        'invoice_footer' => 'Invoice',

    ],

    'send_email' => 'Send by email',
'send_invoice' => 'Send invoice by email',
'email_subject' => 'Email subject',
'default_email_subject' => 'Invoice :invoice - SFA',
'recipients' => 'Recipients',
'no_company_emails' => 'This company has no registered email addresses.',
'documents_to_send' => 'Documents to send',
'pdf_document' => 'Invoice PDF document',
'xml_document' => 'Invoice XML document',

];
